function init_plugin(metadata)
  return {
    after_init = function()
      gengen.log.info('[SiteEnhancer] Loaded ' .. metadata.name)
    end,

    meta_tags = {
      ["gengen-site-plugin"] = "enabled"
    },

    css_assets = { "site-badge.css" },

    body_injection = function()
      return '<div class="plugin-pill plugin-pill--site">Site plugin active</div>'
    end,

    convert = function(content, page)
      if page == nil then
        return content
      end

      if page.isStatic or page.isAsset then
        return content
      end

      local front = page.frontMatter or {}
      local label = front.plugin_label or "Site plugin injected this callout before the content."
      local callout = '<div class="plugin-callout">' .. label .. '</div>'
      return callout .. "\n" .. content
    end,

    after_generate = function()
      gengen.content.write_site('assets/site-plugin.txt', 'Generated by SiteEnhancerPlugin.')
    end
  }
end
