include: package:lints/recommended.yaml

linter:
  rules:
    - camel_case_types
    - always_declare_return_types 
    - sort_pub_dependencies
    - always_use_package_imports 
    - avoid_slow_async_io 
analyzer:
  plugins:
    - dart_code_linter

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    constant_identifier_names: ignore
    non_constant_identifier_names: ignore
    unused_element: error
    unused_field: error
    unused_local_variable: error
    unused_import: error

#dart_code_linter:
#  metrics:
#    cyclomatic-complexity: 20
#    number-of-parameters: 4
#    maximum-nesting-level: 5
#  metrics-exclude:
#    - test/**
#  rules:
#    - avoid-dynamic
#    - avoid-passing-async-when-sync-expected
#    - avoid-redundant-async
#    - avoid-unnecessary-type-assertions
#    - avoid-unnecessary-type-casts
#    - avoid-unrelated-type-assertions
#    - avoid-unused-parameters
#    - avoid-nested-conditional-expressions
#    - newline-before-return
#    - no-boolean-literal-compare
#    - no-empty-block
#    - prefer-trailing-comma
#    - prefer-conditional-expressions
#    - no-equal-then-else
#    - prefer-moving-to-variable
#    - prefer-match-file-name
