targets:
  $default:
    sources:
      - $package$
      - bundle/**
      - lib/**

    builders:
      freezed:
        options:
          union_key: type
          union_value_case: pascal
      gengen:bundle_file_builder:
        enabled: true
builders:
  bundle_file_builder:
    import: "package:gengen/file_bundler.dart"
    builder_factories: ["bundleFileBuilder"]
    build_extensions: {".dart": ["bundle/bundle_data.dart"]}
    auto_apply: dependents
    build_to: source
