function init_plugin(metadata)
  return {
    after_init = function()
      gengen.log.info('[StdlibDemo] Loaded ' .. metadata.name)
    end,

    convert = function(content, page)
      local slug = gengen.util.slugify(page['title'] or '')
      local title = gengen.config.get('title', 'Untitled site')
      return content .. '\n<!-- slug:' .. slug .. ' site:' .. title .. ' -->'
    end,

    after_generate = function()
      local timestamp = os.date('%Y-%m-%d %H:%M:%S')
      local message = 'Generated by ' .. metadata.name .. ' at ' .. timestamp
      gengen.content.write_site('assets/stdlib-demo.txt', message)
    end
  }
end
