function init_plugin(metadata)
  return {
    after_init = function()
      gengen.log.info('[ThemeBanner] Loaded ' .. metadata.name)
    end,

    meta_tags = {
      ["gengen-theme-plugin"] = "enabled"
    },

    css_assets = { "theme-banner.css" },

    body_injection = function()
      return '<div class="plugin-pill plugin-pill--theme">Theme plugin active</div>'
    end,

    after_generate = function()
      gengen.content.write_site('assets/theme-plugin.txt', 'Generated by ThemeBannerPlugin.')
    end
  }
end
